server:
  port: 8079
  servlet:
    context-path: /uaa
  error:
    whitelabel:
      enabled: off
spring:
  application:
    name: oauth2-server
  main:
    banner-mode: off
  datasource:
    url: "jdbc:postgresql://localhost:5432/prore?currentSchema=oauth2"
    driver-class-name: "org.postgresql.Driver"
    hikari:
      pool-name: "auth-server-ds"
      maximum-pool-size: 7
      minimum-idle: 1
    username: "postgres"
    password: ""

logging:
  level:
    root: info
    "org.springframework.security": info
    "org.springframework.jdbc.core": info
    "org.springframework.security.web.FilterChainProxy": debug
