server:
  port: 8081
  servlet:
    context-path: /mvc
spring:
  application:
    name: sso-client1
  main:
    banner-mode: off
  datasource:
    url: "jdbc:postgresql://localhost:5432/sakila?currentSchema=public"
    driver-class-name: "org.postgresql.Driver"
    hikari:
      pool-name: "client1-ds"
      maximum-pool-size: 7
      minimum-idle: 1
      auto-commit: false
    username: "postgres"
    password: ""
  jpa:
    open-in-view: false
  thymeleaf:
    cache: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://auth.example.com:8077"

logging:
  level:
    root: info
    "org.springframework.security.web": info
    "org.springframework.web": debug
    "org.thymeleaf": debug

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
