server:
  address: 127.0.0.1
  port: 8078
  ssl:
    key-store-type: PKCS12
    key-store: "${user.dir}/../certs/services.p12"
    key-store-password: "changeit"
    trust-store-type: JKS
    trust-store: "${user.dir}/../certs/truststore.jks"
    trust-store-password: "changeit"
    enabled: true
  forward-headers-strategy: framework

spring:
  application:
    name: gateway-service-mvc
  main:
    banner-mode: off
  security:
    oauth2:
      client:
        registration:
          client-oidc:
            client-id: "2e8347f2-ccac-4d03-bc2c-cc733ec4da10"
            client-secret: "secret"
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - openid
        provider:
          client-oidc:
            #            issuer-uri: "http://localhost:8077"
            authorization-uri: "https://auth.example.com:8077/oauth2/authorize"
            token-uri: "https://auth.example.com:8077/oauth2/token"
            jwk-set-uri: "https://auth.example.com:8077/oauth2/jwks"
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: client1
              uri: http://localhost:8081
              predicates:
                - Path=/mvc/**
              filters:
                - TokenRelay=
            - id: client2
              uri: http://localhost:8082
              predicates:
                - Path=/flux/**
              filters:
                - TokenRelay=
  web:
    error:
      include-exception: true
      include-stacktrace: always
      include-message: always

logging:
  level:
    root: info
    "org.springframework.cloud.gateway": info
    "org.springframework.security": info
    "org.springframework.security.oauth2": info
    "org.springframework.security.oauth2.core.OAuth2TokenValidator": debug
    "org.springframework.security.oauth2.client": info
    "org.springframework.web": info

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
