server:
  port: 8082
spring:
  webflux:
    base-path: /flux
  application:
    name: sso-client2
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://auth.example.com:8077"

logging:
  level:
    root: info
    "org.springframework.security.web": info

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
