server:
  address: 127.0.0.1
  port: 8082
  ssl:
    key-store-type: PKCS12
    key-store: "${user.dir}/../certs/services.p12"
    key-store-password: "changeit"
    trust-store-type: JKS
    trust-store: "${user.dir}/../certs/truststore.jks"
    trust-store-password: "changeit"
    enabled: true

spring:
  webflux:
    base-path: /flux
  application:
    name: sso-client2
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: "file:${user.dir}/../certs/gateway-public.pem"
  threads:
    virtual:
      enabled: true

gateway:
  issuer-uri: "https://sso.example.com:8040"

logging:
  level:
    root: info
    "org.springframework.security.web": info

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
