server:
  port: 8082
spring:
  application:
    name: sso-client2
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8079/uaa"
logging:
  level:
    root: info
    "org.springframework.security.web": info
